# Generated by Django 4.0.4 on 2022-04-23 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='date',
            new_name='end_date',
        ),
    ]
