# Generated by Django 4.0.4 on 2022-04-23 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
        ('projects', '0002_remove_programminglanguage_project_project_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='devloper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer'),
        ),
    ]
